### ISSUE TITLE
Compilation Error: 'None' has no attribute 'options'

### ISSUE THREAD

**Issue by JoeryV** [EqualExperts/dbt-unit-testing#129]
My unit test works when I run `dbt test -s test_model.sql`.

When I try to `git commit` it, however, I get the error: 

```
'None' has no attribute 'options'
  
  > in macro merge_configs (macros/utils.sql)
  > called by macro build_mocks_and_expectations (macros/tests.sql)
  > called by macro test (macros/tests.sql)
  > called by <Unknown>
```

Based on looking around in the `macros/tests.sql` file, it seems like `{% set mocks_and_expectations_json_str = caller() %}` might be returning None. 

Being a Jinja rookie, it is unclear to me 
(1) if this is actually the cause of the error and 
(2) why this would be the case. 

Any help with debugging would be much appreciated! 

Versions:
dbt v1.4
dbt-unit-testing v0.2.7

**Comment by JoeryV** [comment]
I don't know what exactly fixed it, but it might have been either changing the default settings for `unit_tests_config` var or having added the unit_testing folder to our `.sqlfluffignore` file (sqlfluff gets run in our pre-commit hook).

**Comment by yoheimiyamoto** [comment]
I got the same situation. When I added the comment to the test code, I got an error.

```sql
{{ config(tags=["unit-test"]) }}

{% set options = {"include_missing_columns": False, "use_database_models": False} %}

{% call dbt_unit_testing.test("mart__partition_table", "partition_table", options) %}
    {% call dbt_unit_testing.mock_source("partition", "partition_test") %}
        name    | _partitiondate
        "hello" | date("2023-01-01")
        "world" | date("2023-01-01")
    {% endcall %}

    /* Adding a comment leads to an error */
    {% call dbt_unit_testing.mock_ref("stg_seed__users", options) %}
        name    | gender | birthday
        "hello" | "M"    | date("2023-01-01")
        "world" | "M"    | date("2023-01-02")
    {% endcall %}
    
    {% call dbt_unit_testing.expect() %}
        name    | birthday
        "hello" | date("2023-01-01")
        "world" | date("2023-01-02")
    {% endcall %}

{% endcall %}
```

**Comment by psousa50** [comment]
Hello everyone,

As pointed out by @yoheimiyamoto, the issue seems to be with the comment syntax used in the code. The problem is that Jinja, the language used for writing dbt tests, does not support this type of comment syntax.

To resolve this issue, please refer to the dbt documentation on how to use comments in Jinja. You can find more information on this topic at the following [link](https://docs.getdbt.com/docs/build/jinja-macros#:~:text=Comments%20%7B%23%20...%20%23%7D%3A%20Jinja%20comments%20are%20used%20to%20prevent%20the%20text%20within%20the%20comment%20from%20compiling).

Hope this helps! Let us know if you have any further questions or concerns.

**Comment by JackWolverson** [comment]
> I don't know what exactly fixed it, but it might have been either changing the default settings for `unit_tests_config` var or having added the unit_testing folder to our `.sqlfluffignore` file (sqlfluff gets run in our pre-commit hook).

what did you change ? in the config ? i have dbt-packages already in .sqlfluff ignore. i dont have comments in any models / unit tests currently but am getting the same error
