### ISSUE TITLE
Is there a way to run post-hooks when testing a model?

### ISSUE THREAD

**Issue by abi-mutinex** [EqualExperts/dbt-unit-testing#207]
The model I'm testing has a post-hook. It is not being run right now so the testing is sort of incomplete. Is there a way to test the post-hook?

**Comment by cdiniz** [comment]
Hi @abi-mutinex Currently we don't have a way to test post-hooks in the framework, we focused on the models.
Since hooks are different pieces of SQL and you can do complex stuff like unloading models to s3 (from dbt's documentation), it's complex to add them with our current setup. Thanks for raising it anyway.
