### ISSUE TITLE
unit tests run 6 times slower because of round trip calls to the database

### ISSUE THREAD

**Issue by DrValani** [EqualExperts/dbt-unit-testing#69]
We are currently porting over to using the latest version of this library, and have found that our unit tests take 6 times longer to run than before. 

Possible feature request to make create pure unit tests based off just the models and no calls to a database.

**Comment by caoilte** [comment]
I would go further and argue that because version 1.0 of the library requires connecting to the database it isn't actually doing unit testing. Slower test runs is one consequence. Another is less flexibility about how and when tests are run (eg we currently like to run our unit tests on branches before the associated database changes are made).

**Comment by cdiniz** [comment]
Hi @caoilte and @DrValani 

Thank you for your feedback!

We introduced a feature in our unit test features that is using database calls (but just in the last scenario).

With our old framework, we were doing just 1 db call per test, which is the fastest way.

Although, when you were doing a mock, you needed to do something similar to this

```
select 'some_field_used_in_test',
'' as unused_field_in_test_but_necessary_for_the_mock,
'' as unused_field_2_in_test_but_necessary_for_the_mock
```

Sometimes you ended up having 10-20 fields that were not used for the test setup but used just for compilation purposes. 

What we introduced in the newer versions of the framework, is **having the unused fields in tests but necessary for the mocks being created/introduced by the framework**, so you can have cleaner tests.

To introduce this obviously that we need to pay a price because we need to inspect the models/sources/seeds.
We're using the following strategy:

**Fast Version**, without the need to go to the database: we are taking the columns out from the yml files that describe sources, seeds and models.

**Slower version** (worst-case scenario, not ideal at all in my point-of-view): we will connect to the database, we'll see if you have the models or sources created and we'll inspect the models.

I'm assuming that you don't have the columns of your sources documented so you are experiencing more queries than before.

Then I recommend you try to document your columns of models/sources if it's the case and see how are the timings. 

Also, after thinking about this, we can actually have a mocking strategy which is not to do anything extra on the mocks, so the freedom is on the user, if there's the need to put null fields or empty strings, that's the user responsibility. 
I'll investigate it and possibly create a pull request on the next days.

**Comment by cdiniz** [comment]
A new mocking strategy was introduced in #70 which makes the tests faster without any extra db queries.
