### ISSUE TITLE
Do you plan to enhance it for incremental models?

### ISSUE THREAD

**Issue by basrisahin** [EqualExperts/dbt-unit-testing#83]
we could not be sure incremental materialization strategies is working well or missing sth so thats why I am asking.

**Comment by LiliaBh** [comment]
Hi, 
same question. Incremental models could not be tested, is there a workaround?

**Comment by jkaczanowski-rest** [comment]
+1
an dbt_unit_testing.mock_initial() section? and/or some way to mock {{ 'this' }}?

**Comment by kborn** [comment]
+1 on this as well

**Comment by hugohjerten** [comment]
+1! I love this package! But without support for incremental models, we will not be able to test our most important models 😢

**Comment by psousa50** [comment]
Hello everyone,

We have created a new branch proposing an implementation of "dbt-unit-testing" that supports "incremental-models".

As you will see, our solution is a bit 'intrusive', at least for those we prefer to redefine the "ref" macro instead of using "dbt_init_testing.ref" on your models. Here you'll have to use some "dbt_init_testing.xxx", as explained in the README.
 
We did try to find a less intrusive solution, but our attempts seemed hacky, so we decided to keep it like this.

We are eager to hear your feedback and suggestions, so please give it a try and let us know your thoughts. We hope it will save you time and prove useful.

To access this branch, you will need to change the revision of the package as follows:

```
packages:
  - git: "https://github.com/EqualExperts/dbt-unit-testing"
    revision: e4a93ebd08ccd388d212b1ec636da2e467db12b9
```

Please do not hesitate to share your feedback with us. Thank you!

**Comment by p0tr3c** [comment]
Hey, the implemented PR works great. Is there anything I could help with trying to get this released?
